version: '3.8'
name: readjoy
services:
  server:
    env_file: .env
    container_name: readjoy-service
    build: ./
    restart: always
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
      - DB_PORT=$DB_PORT
      - DB_CONNECTION_LIMIT=4
      - REDIS_HOST=redis
      - REDIS_PORT=$REDIS_DOCKER_PORT
      - TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
      - BINANCE_API_KEY=$BINANCE_API_KEY
      - BINANCE_API_SECRET=$BINANCE_API_SECRET
      - BINANCE_SUB_API_KEY=$BINANCE_SUB_API_KEY
      - BINANCE_SUB_API_SECRET=$BINANCE_SUB_API_SECRET
      - BINANCE_SUB_API_KEY_2=$BINANCE_SUB_API_KEY_2
      - BINANCE_SUB_API_SECRET_2=$BINANCE_SUB_API_SECRET_2
    networks:
      - bridge
      - database-bridge
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - $REDIS_LOCAL_PORT:$REDIS_DOCKER_PORT
    networks:
      - bridge

networks:
  database-bridge:
    external: true
  bridge:
